- alias: 'Turn on lights when home at night'
  trigger:
    platform: sun
    event: sunset
    offset: "-03:00:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: home
  action:
    service: homeassistant.turn_on
    entity_id: ["light.living_room","light.kitchen"]
