- alias: 'Turn on lights when home at night'
  trigger:
    platform: sun
    event: sunset
    offset: "-03:00:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: home
  action:
    service: homeassistant.turn_on
    entity_id: ["light.living_room","light.kitchen"]
- alias: 'Turn on bedroom AC when cooling and door closes'
  trigger:
    platform: state
    entity_id: sensor.bedroom_door
    from: 'open'
    to: 'closed'
  condition:
    condition: template
    value_template: "{{ is_state('switch.swamp_cooler', 'on') }}"
  action:
    service: homeassistant.turn_on
    entity_id: switch.bedroom_ac
- alias: 'Turn off bedroom AC when cooling and door opens'
  trigger:
    platform: state
    entity_id: sensor.bedroom_door
    from: 'closed'
    to: 'open'
  condition:
    condition: template
    value_template: "{{ is_state('switch.swamp_cooler', 'on') }}"
  action:
    service: homeassistant.turn_off
    entity_id: switch.bedroom_ac
