- platform: mqtt
  name: Bedroom Temperature
  state_topic: "smartthings/Bedroom Door/temperature"
  type: temperature
  unit_of_measurement: '째F'

- platform: mqtt
  name: Bedroom Door
  state_topic: "smartthings/Bedroom Door/contact"

- platform: mqtt
  name: Kitchen Temperature
  state_topic: "smartthings/Kitchen Door/temperature"
  type: temperature
  unit_of_measurement: '째F'

- platform: mqtt
  name: Kitchen Door
  state_topic: "smartthings/Kitchen Door/contact"

- platform: mqtt
  name: Living Room Temperature
  state_topic: "smartthings/Living Room Door/temperature"
  type: temperature
  unit_of_measurement: '째F'

- platform: mqtt
  name: Living Room Door
  state_topic: "smartthings/Living Room Door/contact"

- platform: darksky
  name: Outside
  api_key: !secret darksky_key
  monitored_conditions:
    - summary
    - icon
    - humidity
    - temperature

- platform: swamp_efficiency
  humidity_sensor: sensor.outside_humidity
  temperature_sensor: sensor.outside_temperature

- platform: template
  sensors:
    house:
      friendly_name: 'House'
      unit_of_measurement: '째F'
      value_template: >-
        {{ ((float(states.sensor.living_room_temperature.state) + float(states.sensor.bedroom_temperature.state) + float(states.sensor.kitchen_temperature.state)) / 3) | round(1) }}
