- platform: template
  switches:
    air_conditioning:
      friendly_name: Air Conditioning
      value_template: "{{ is_state('switch.bedroom_ac', 'on') and is_state('switch.kitchen_ac', 'on') and is_state('switch.living_room_ac', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.bedroom_ac
          - switch.kitchen_ac
          - switch.living_room_ac
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.bedroom_ac
          - switch.living_room_ac
          - switch.kitchen_ac
    use_ac_instead:
      friendly_name: Use AC Instead
      value_template: "{{ is_state('switch.air_conditioning', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.switch_to_ac
      turn_off:
        service: script.turn_on
        entity_id: script.switch_to_swamp
